name: shellcheck

on:
  push:
    paths:
      - "commands/shell/**"
      - ".github/workflows/shellcheck.yml"
  pull_request:
    types: ["opened", "synchronize", "reopened"]
    paths:
      - "commands/shell/**"
      - ".github/workflows/shellcheck.yml"

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Run shellcheck
        run: shellcheck commands/shell/*

